### ISSUE TITLE
Can't change Language

### ISSUE THREAD

**Issue by TheRagingArden** [debnet/fallout#4]
Hi there I've got the django python side running on my windows 10 machine and the site is in french, how do I change it so that its in English by default?

**Comment by debnet** [comment]
Django aims to detect the language of the browser. 
Currently, this application is completly translated in english but I guess it defaults to french is your are neither french or english. 
You can override the default language in `rpg/settings.py` by changing the environment variable `DJANGO_LANGUAGE_CODE` to `en`.

Exemple in one line:
`DJANGO_LANGUAGE_CODE=en python manage.py runserver`

**Comment by debnet** [comment]
Oh, don't forget to compile translation before running this application.
https://docs.djangoproject.com/en/3.0/topics/i18n/translation/#compiling-message-files

`python manage.py compilemessages`

**Comment by TheRagingArden** [comment]
Thanks so much its translated now I had the language set in the python script but I didn't compile it.
